### ISSUE TITLE
Configuration documentation for kong-plugin-ngsi-ishare-policies

### ISSUE THREAD

**Issue by tarmo-profi** [FIWARE/kong-plugins-fiware#19]
Hello,

I see that certificates are configured as documentation advices:

```
            x5c: |
              -----BEGIN CERTIFICATE-----
              <SERVICE_PROVIDER_CERT>
              -----END CERTIFICATE-----
              ...<INTERMEDIATES>...
              -----BEGIN CERTIFICATE-----
              <ROOT_CA_CERT>
              -----END CERTIFICATE-----
```

The INTERMEDIATES certificates are missing the BEGIN - END CERTIFICATE lines. Is this supposed to look like that?

**Comment by dwendland** [comment]
This is just a placeholder, since there can be several intermediates. Of course every single certificate requires the BEGIN/END lines.
